### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ellermister** [Archeb/opentrace#32]
2023/11/20 18:08:05 api.ip.sb 璇锋眰瓒呮椂(2s)锛岃鍒囨崲鍏朵粬API浣跨敤
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x117d932]

goroutine 278 [running]:
github.com/nxtrace/NTrace-core/printer.applyLangSetting(0x1329240?)
	github.com/nxtrace/NTrace-core/printer/basic.go:94 +0x12
github.com/nxtrace/NTrace-core/printer.EasyPrinter(0xc0000d0a68, 0x5)
	github.com/nxtrace/NTrace-core/printer/easy.go:15 +0xd6
github.com/nxtrace/NTrace-core/trace.(*ICMPTracer).PrintFunc(0xc0000d09a0)
	github.com/nxtrace/NTrace-core/trace/icmp_ipv4.go:48 +0xfd
created by github.com/nxtrace/NTrace-core/trace.(*ICMPTracer).Execute in goroutine 1
	github.com/nxtrace/NTrace-core/trace/icmp_ipv4.go:85 +0x28b

**Comment by ellermister** [comment]
你是bot啊，秒回复。

顺便再问问，能不能把winmtr的路由整合进来，那个一秒就能出来所有的路由节点，CPP的代码，我看的不是很懂；之前besttrace收费时就像搞一个这种项目，一直懒，没想到有人已经做了。

另外地图建议 Google map，解决次数收费的问题，可以拦截webview的网络请求把，GoogleJS产生的几个参数改掉就可以去掉地图版权阴影，属于hacker方式。
